// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: PHC_RET6

#include "../ui.h"

void ui_MotorControlScreen_screen_init(void)
{
    ui_MotorControlScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MotorControlScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Forward_and_backward_panel = lv_obj_create(ui_MotorControlScreen);
    lv_obj_set_width(ui_Forward_and_backward_panel, lv_pct(100));
    lv_obj_set_height(ui_Forward_and_backward_panel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Forward_and_backward_panel, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Forward_and_backward_panel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Forward_and_backward_panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Forward_and_backward_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Forward_and_backward_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Forward_and_backward_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Forward_and_backward_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Forward_and_backward_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Forward_and_backward_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Forward_and_backward_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Forward_and_backward_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Forward_and_backwardLabel = lv_label_create(ui_Forward_and_backward_panel);
    lv_obj_set_width(ui_Forward_and_backwardLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Forward_and_backwardLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Forward_and_backwardLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Forward_and_backwardLabel, "前后");
    lv_obj_set_style_text_font(ui_Forward_and_backwardLabel, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Forward_and_backward = lv_label_create(ui_Forward_and_backward_panel);
    lv_obj_set_width(ui_Forward_and_backward, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Forward_and_backward, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Forward_and_backward, "0.0");
    lv_obj_add_flag(ui_Forward_and_backward, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_Forward_and_backward, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Forward_and_backward, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Forward_and_backward, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_Forward_and_backward, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Forward_and_backward, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_Forward_and_backward, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_opa(ui_Forward_and_backward, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_bg_color(ui_Forward_and_backward, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_bg_opa(ui_Forward_and_backward, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_MotorSwitch1 = lv_switch_create(ui_MotorControlScreen);
    lv_obj_set_width(ui_MotorSwitch1, 26);
    lv_obj_set_height(ui_MotorSwitch1, 14);
    lv_obj_set_align(ui_MotorSwitch1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_state(ui_MotorSwitch1, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_bg_color(ui_MotorSwitch1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MotorSwitch1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MotorSwitch1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MotorSwitch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MotorSwitch1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_MotorSwitch1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MotorSwitch1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_MotorSwitch1, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_MotorSwitch1, 1, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_MotorSwitch1, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    lv_obj_set_style_bg_color(ui_MotorSwitch1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MotorSwitch1, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_pad_left(ui_MotorSwitch1, -2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MotorSwitch1, -2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MotorSwitch1, -2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MotorSwitch1, -2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MotorSwitch1, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MotorSwitch1, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_backButton1 = lv_btn_create(ui_MotorControlScreen);
    lv_obj_set_width(ui_backButton1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backButton1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_backButton1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_backButton1, LV_OBJ_FLAG_EVENT_BUBBLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_backButton1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backButton1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_backButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_backButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_backButton1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_backButton1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_backButton1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_backButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_backButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_bg_opa(ui_backButton1, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Label7 = lv_label_create(ui_backButton1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "back");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Left_turn_right_turn_panel = lv_obj_create(ui_MotorControlScreen);
    lv_obj_set_width(ui_Left_turn_right_turn_panel, lv_pct(100));
    lv_obj_set_height(ui_Left_turn_right_turn_panel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Left_turn_right_turn_panel, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_Left_turn_right_turn_panel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Left_turn_right_turn_panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Left_turn_right_turn_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Left_turn_right_turn_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Left_turn_right_turn_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Left_turn_right_turn_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Left_turn_right_turn_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Left_turn_right_turn_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Left_turn_right_turn_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Left_turn_right_turn_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Left_turn_right_turnLabel = lv_label_create(ui_Left_turn_right_turn_panel);
    lv_obj_set_width(ui_Left_turn_right_turnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Left_turn_right_turnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Left_turn_right_turnLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Left_turn_right_turnLabel, "左右");
    lv_obj_set_style_text_font(ui_Left_turn_right_turnLabel, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Left_turn_and_right_turn = lv_label_create(ui_Left_turn_right_turn_panel);
    lv_obj_set_width(ui_Left_turn_and_right_turn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Left_turn_and_right_turn, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Left_turn_and_right_turn, "0.0");
    lv_obj_add_flag(ui_Left_turn_and_right_turn, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_Left_turn_and_right_turn, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Left_turn_and_right_turn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Left_turn_and_right_turn, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_Left_turn_and_right_turn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Left_turn_and_right_turn, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_Left_turn_and_right_turn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_opa(ui_Left_turn_and_right_turn, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_bg_color(ui_Left_turn_and_right_turn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_bg_opa(ui_Left_turn_and_right_turn, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    lv_obj_add_event_cb(ui_Forward_and_backward, ui_event_Forward_and_backward, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MotorSwitch1, ui_event_MotorSwitch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backButton1, ui_event_backButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Left_turn_and_right_turn, ui_event_Left_turn_and_right_turn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MotorControlScreen, ui_event_MotorControlScreen, LV_EVENT_ALL, NULL);

}
