// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: PHC_RET6

#include "../ui.h"

void ui_pidControlScreen_screen_init(void)
{
    ui_pidControlScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_pidControlScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MotorSwitch = lv_switch_create(ui_pidControlScreen);
    lv_obj_set_width(ui_MotorSwitch, 26);
    lv_obj_set_height(ui_MotorSwitch, 14);
    lv_obj_set_x(ui_MotorSwitch, 46);
    lv_obj_set_y(ui_MotorSwitch, 19);
    lv_obj_set_align(ui_MotorSwitch, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_MotorSwitch, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_bg_color(ui_MotorSwitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MotorSwitch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MotorSwitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MotorSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MotorSwitch, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_MotorSwitch, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MotorSwitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_MotorSwitch, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_MotorSwitch, 1, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_MotorSwitch, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    lv_obj_set_style_bg_color(ui_MotorSwitch, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MotorSwitch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_pad_left(ui_MotorSwitch, -2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MotorSwitch, -2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MotorSwitch, -2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MotorSwitch, -2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MotorSwitch, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MotorSwitch, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_PIDControl = lv_obj_create(ui_pidControlScreen);
    lv_obj_set_width(ui_PIDControl, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_PIDControl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PIDControl, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_PIDControl, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PIDControl, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PIDControl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PIDControl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PIDControl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PIDControl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PIDControl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PIDControl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PIDControl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PIDControl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PIDControl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PIDControl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_P = lv_label_create(ui_PIDControl);
    lv_obj_set_width(ui_P, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_P, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_P, "P:0.0");
    lv_obj_add_flag(ui_P, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_P, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_P, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_P, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_P, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_P, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_P, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_opa(ui_P, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_bg_color(ui_P, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_bg_opa(ui_P, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_I = lv_label_create(ui_PIDControl);
    lv_obj_set_width(ui_I, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_I, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_I, LV_ALIGN_CENTER);
    lv_label_set_text(ui_I, "I:0.0");
    lv_obj_add_flag(ui_I, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_I, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_I, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_I, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_I, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_I, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_D = lv_label_create(ui_PIDControl);
    lv_obj_set_width(ui_D, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_D, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_D, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_D, "D:0.0");
    lv_obj_add_flag(ui_D, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_D, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_D, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_D, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_D, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_D, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_zeroButton = lv_btn_create(ui_pidControlScreen);
    lv_obj_set_width(ui_zeroButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_zeroButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_zeroButton, 0);
    lv_obj_set_y(ui_zeroButton, -5);
    lv_obj_set_align(ui_zeroButton, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_zeroButton, LV_OBJ_FLAG_EVENT_BUBBLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_zeroButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_zeroButton, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_zeroButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_zeroButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_zeroButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_zeroButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_zeroButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_zeroButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_zeroButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_zeroButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_zeroButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_zeroButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_bg_opa(ui_zeroButton, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Label1 = lv_label_create(ui_zeroButton);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "清零");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_backButton = lv_btn_create(ui_pidControlScreen);
    lv_obj_set_width(ui_backButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_backButton, 0);
    lv_obj_set_y(ui_backButton, -5);
    lv_obj_set_align(ui_backButton, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_backButton, LV_OBJ_FLAG_EVENT_BUBBLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_backButton, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_backButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_backButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_backButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_backButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_backButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_backButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_backButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_bg_opa(ui_backButton, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Label3 = lv_label_create(ui_backButton);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "back");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_chinese, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_PIDinput = lv_label_create(ui_pidControlScreen);
    lv_obj_set_width(ui_PIDinput, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PIDinput, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PIDinput, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_PIDinput, "in:0.0");

    lv_obj_add_event_cb(ui_MotorSwitch, ui_event_MotorSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_P, ui_event_P, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_I, ui_event_I, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_D, ui_event_D, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_zeroButton, ui_event_zeroButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backButton, ui_event_backButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pidControlScreen, ui_event_pidControlScreen, LV_EVENT_ALL, NULL);

}
