// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: PHC_RET6

#include "../ui.h"

void ui_tsl1401Screen_screen_init(void)
{
    ui_tsl1401Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_tsl1401Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TSL1401Chart = lv_chart_create(ui_tsl1401Screen);
    lv_obj_set_width(ui_TSL1401Chart, 128);
    lv_obj_set_height(ui_TSL1401Chart, 64);
    lv_obj_set_align(ui_TSL1401Chart, LV_ALIGN_TOP_MID);
    lv_chart_set_type(ui_TSL1401Chart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_TSL1401Chart, 128);
    lv_chart_set_div_line_count(ui_TSL1401Chart, 2, 5);
    lv_chart_set_axis_tick(ui_TSL1401Chart, LV_CHART_AXIS_PRIMARY_X, 0, 5, 0, 2, false, 50);
    lv_chart_set_axis_tick(ui_TSL1401Chart, LV_CHART_AXIS_PRIMARY_Y, 0, 5, 0, 2, false, 50);
    lv_chart_set_axis_tick(ui_TSL1401Chart, LV_CHART_AXIS_SECONDARY_Y, 0, 5, 0, 2, false, 25);
    lv_chart_series_t * ui_TSL1401Chart_series_1 = lv_chart_add_series(ui_TSL1401Chart, lv_color_hex(0xFFFFFF),
                                                                       LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_TSL1401Chart_series_1_array[] = { 0 };
    lv_chart_set_ext_y_array(ui_TSL1401Chart, ui_TSL1401Chart_series_1, ui_TSL1401Chart_series_1_array);
    lv_obj_set_style_bg_color(ui_TSL1401Chart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TSL1401Chart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TSL1401Chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_TSL1401Chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TSL1401Chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TSL1401Chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TSL1401Chart, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TSL1401Chart, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_line_width(ui_TSL1401Chart, 1, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_tsl1401Screen, ui_event_tsl1401Screen, LV_EVENT_ALL, NULL);

}
