// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: PHC_RET6

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
void ui_event_mainScreen(lv_event_t * e);
lv_obj_t * ui_mainScreen;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Label5;
lv_obj_t * ui_batBar;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Spinner1;
void ui_event_toControlButton(lv_event_t * e);
lv_obj_t * ui_toControlButton;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Spinner2;
void ui_event_toPidButton(lv_event_t * e);
lv_obj_t * ui_toPidButton;
lv_obj_t * ui_Label4;

// SCREEN: ui_pidControlScreen
void ui_pidControlScreen_screen_init(void);
void ui_event_pidControlScreen(lv_event_t * e);
lv_obj_t * ui_pidControlScreen;
lv_obj_t * ui_Uprightring;
void ui_event_UprightringP(lv_event_t * e);
lv_obj_t * ui_UprightringP;
lv_obj_t * ui_UprightringLabel;
void ui_event_UprightringD(lv_event_t * e);
lv_obj_t * ui_UprightringD;
lv_obj_t * ui_Speedloop;
void ui_event_SpeedloopP(lv_event_t * e);
lv_obj_t * ui_SpeedloopP;
lv_obj_t * ui_SpeedloopLabel;
void ui_event_SpeedloopI(lv_event_t * e);
lv_obj_t * ui_SpeedloopI;
void ui_event_MotorSwitch(lv_event_t * e);
lv_obj_t * ui_MotorSwitch;
lv_obj_t * ui_Steeringring;
void ui_event_SteeringringP(lv_event_t * e);
lv_obj_t * ui_SteeringringP;
void ui_event_SteeringringD(lv_event_t * e);
lv_obj_t * ui_SteeringringD;
void ui_event_SteeringringI(lv_event_t * e);
lv_obj_t * ui_SteeringringI;
void ui_event_zeroButton(lv_event_t * e);
lv_obj_t * ui_zeroButton;
lv_obj_t * ui_Label1;
void ui_event_backButton(lv_event_t * e);
lv_obj_t * ui_backButton;
lv_obj_t * ui_Label3;

// SCREEN: ui_MotorControlScreen
void ui_MotorControlScreen_screen_init(void);
void ui_event_MotorControlScreen(lv_event_t * e);
lv_obj_t * ui_MotorControlScreen;
lv_obj_t * ui_Forward_and_backward_panel;
lv_obj_t * ui_Forward_and_backwardLabel;
void ui_event_Forward_and_backward(lv_event_t * e);
lv_obj_t * ui_Forward_and_backward;
void ui_event_MotorSwitch1(lv_event_t * e);
lv_obj_t * ui_MotorSwitch1;
void ui_event_backButton1(lv_event_t * e);
lv_obj_t * ui_backButton1;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Left_turn_right_turn_panel;
lv_obj_t * ui_Left_turn_right_turnLabel;
void ui_event_Left_turn_and_right_turn(lv_event_t * e);
lv_obj_t * ui_Left_turn_and_right_turn;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 8
    // #error "LV_COLOR_DEPTH should be 8bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_mainScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        mainScreen_init(e);
    }
}
void ui_event_toControlButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MotorControlScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_MotorControlScreen_screen_init);
    }
}
void ui_event_toPidButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_pidControlScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_pidControlScreen_screen_init);
    }
}
void ui_event_pidControlScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        pidControlScreen_init(e);
    }
}
void ui_event_UprightringP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_LEFT) {
        UprightringP_Left(e);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_RIGHT) {
        UprightringP_Right(e);
    }
}
void ui_event_UprightringD(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_LEFT) {
        UprightringD_Left(e);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_RIGHT) {
        UprightringD_Right(e);
    }
}
void ui_event_SpeedloopP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_LEFT) {
        SpeedloopP_Left(e);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_RIGHT) {
        SpeedloopP_Right(e);
    }
}
void ui_event_SpeedloopI(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_LEFT) {
        SpeedloopI_Left(e);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_RIGHT) {
        SpeedloopI_Right(e);
    }
}
void ui_event_MotorSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        Motor_switch_checked(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        Motor_switch_unchecked(e);
    }
}
void ui_event_SteeringringP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_LEFT) {
        SteeringRingP_Left(e);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_RIGHT) {
        SteeringRingP_Right(e);
    }
}
void ui_event_SteeringringD(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_LEFT) {
        SteeringRingD_Left(e);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_RIGHT) {
        SteeringRingD_Right(e);
    }
}
void ui_event_SteeringringI(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_LEFT) {
        SteeringRingI_Left(e);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_RIGHT) {
        SteeringRingI_Right(e);
    }
}
void ui_event_zeroButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        zero(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_state_modify(ui_Label1, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_state_modify(ui_Label1, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_backButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_mainScreen_screen_init);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_state_modify(ui_Label3, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_state_modify(ui_Label3, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_MotorControlScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        MotorControlScreen_load_start(e);
    }
}
void ui_event_Forward_and_backward(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_LEFT) {
        Forwardandbackward_Left(e);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_RIGHT) {
        Forwardandbackward_Right(e);
    }
}
void ui_event_MotorSwitch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        Motor_switch_checked(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        Motor_switch_unchecked(e);
    }
}
void ui_event_backButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_mainScreen_screen_init);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_state_modify(ui_Label7, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_state_modify(ui_Label7, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_Left_turn_and_right_turn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_LEFT) {
        Leftturnandrightturn_Left(e);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_RIGHT) {
        Leftturnandrightturn_Right(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_mainScreen_screen_init();
    ui_pidControlScreen_screen_init();
    ui_MotorControlScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_mainScreen);
}
