// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: PHC_RET6

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void mainScreen_init(lv_event_t * e);
void pidControlScreen_load_start(lv_event_t * e);
void pidControlScreen_unload_start(lv_event_t * e);
void Motor_switch_checked(lv_event_t * e);
void Motor_switch_unchecked(lv_event_t * e);
void P_Left(lv_event_t * e);
void P_Right(lv_event_t * e);
void I_Left(lv_event_t * e);
void I_Right(lv_event_t * e);
void D_Left(lv_event_t * e);
void D_Right(lv_event_t * e);
void zero(lv_event_t * e);
void MotorControlScreen_load_start(lv_event_t * e);
void Forwardandbackward_Left(lv_event_t * e);
void Forwardandbackward_Right(lv_event_t * e);
void Leftturnandrightturn_Left(lv_event_t * e);
void Leftturnandrightturn_Right(lv_event_t * e);
void TSL1401Screen_load_start(lv_event_t * e);
void TSL1401Screen_unload_start(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
