// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: PHC_RET6

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Screen1_init(lv_event_t * e);
void UprightringP_Left(lv_event_t * e);
void UprightringP_Right(lv_event_t * e);
void UprightringD_Left(lv_event_t * e);
void UprightringD_Right(lv_event_t * e);
void SpeedloopP_Left(lv_event_t * e);
void SpeedloopP_Right(lv_event_t * e);
void SpeedloopI_Left(lv_event_t * e);
void SpeedloopI_Right(lv_event_t * e);
void Motor_switch_checked(lv_event_t * e);
void Motor_switch_unchecked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
